apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnplaterec_frontend
  labels:
    app: vnplaterec_frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnplaterec_frontend
  template:
    metadata:
      labels:
        app: vnplaterec_frontend
    spec:
      containers:
      - name: vnplaterec_frontend
        image: cnmeow/vnplaterec_frontend:latest
        ports:
        - containerPort: 2106