apiVersion: v1
kind: Service
metadata:
  name: vnplaterec-frontend
  labels:
    app: vnplaterec-frontend
spec:
  type: NodePort
  ports:
  - port: 2106
    targetPort: 2106
    nodePort: 30007
  selector:
    app: vnplaterec-frontend